version: "3"
services:
  ui:
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode: host
    restart: always
    ports:
      - ${NEXT_PUBLIC_PORT}:${NEXT_PUBLIC_PORT}
    env_file:
      - .env
